send("buy two handed sword")
send("buy two handed sword")
send("buy two handed sword")
send("buy two handed sword")
send("buy two handed sword")
send("buy two handed sword")
send("buy two handed sword")
send("buy two handed sword")
send("buy two handed sword")
send("buy two handed sword")
send("buy two handed sword")
send("buy two handed sword")
send("buy two handed sword")
send("buy two handed sword")
send("buy two handed sword")
send("buy two handed sword")
send("buy two handed sword")
send("home")
send("guild")
send("e")
send("e")
send("e")
send("e")
send("u")
send("n")
send("incorporate all")
send("s")
send("d")
send("w")
send("w")
send("w")
send("w")
send("home")
send("smithy")
send("buy two handed sword")
send("buy two handed sword")
send("buy two handed sword")
send("buy two handed sword")
send("buy two handed sword")
send("buy two handed sword")
send("buy two handed sword")
send("buy two handed sword")
send("buy two handed sword")
send("buy two handed sword")
send("buy two handed sword")
send("buy two handed sword")
send("buy two handed sword")
send("buy two handed sword")
send("buy two handed sword")
send("buy two handed sword")
send("buy two handed sword")
send("home")
send("guild")
send("e")
send("e")
send("e")
send("e")
send("u")
send("n")
send("incorporate all")
send("s")
send("d")
send("w")
send("w")
send("w")
send("w")
send("home")
send("smithy")
send("buy two handed sword")
send("buy tower shield")
send("buy tower shield")
send("buy tower shield")
send("buy tower shield")
send("buy tower shield")
send("buy tower shield")
send("buy tower shield")
send("buy tower shield")
send("buy tower shield")
send("buy tower shield")
send("buy tower shield")
send("buy tower shield")
send("buy tower shield")
send("buy tower shield")
send("buy tower shield")
send("buy tower shield")
send("buy tower shield")
send("buy tower shield")
send("buy tower shield")
send("home")
send("guild")
send("e")
send("e")
send("e")
send("e")
send("u")
send("n")
send("incorporate all")
send("s")
send("d")
send("w")
send("w")
send("w")
send("w")
send("home")
send("smithy")
send("buy tower shield")
send("buy tower shield")
send("buy tower shield")
send("buy tower shield")
send("buy tower shield")
send("buy tower shield")
send("buy tower shield")
send("buy tower shield")
send("buy tower shield")
send("buy tower shield")
send("buy tower shield")
send("buy tower shield")
send("buy tower shield")
send("buy tower shield")
send("buy tower shield")
send("buy tower shield")
send("buy tower shield")
send("buy tower shield")
send("buy tower shield")
send("home")
send("guild")
send("e")
send("e")
send("e")
send("e")
send("u")
send("n")
send("incorporate all")
send("s")
send("d")
send("w")
send("w")
send("w")
send("w")
send("home")
send("smithy")
send("buy tower shield")
send("buy tower shield")
send("buy tower shield")
send("buy tower shield")
send("buy tower shield")
send("buy tower shield")
send("buy tower shield")
send("buy tower shield")
send("buy tower shield")
send("buy tower shield")
send("buy tower shield")
send("buy tower shield")
send("buy tower shield")
send("buy two handed sword")
send("buy two handed sword")
send("buy two handed sword")
send("buy two handed sword")
send("buy two handed sword")
send("buy two handed sword")
send("buy two handed sword")
send("home")
send("guild")
send("e")
send("e")
send("e")
send("e")
send("u")
send("n")
send("incorporate all")
send("s")
send("d")
send("w")
send("w")
send("w")
send("w")
send("home")
send("smithy")
send("buy tower shield")
send("buy tower shield")
send("buy tower shield")
send("buy tower shield")
send("buy tower shield")
send("buy tower shield")
send("buy tower shield")
send("buy tower shield")
send("buy tower shield")
send("buy tower shield")
send("buy two handed sword")
send("buy two handed sword")
send("buy two handed sword")
send("buy two handed sword")
send("buy two handed sword")
send("buy two handed sword")
send("buy two handed sword")
send("buy two handed sword")
send("buy two handed sword")
send("buy two handed sword")
send("home")
send("guild")
send("e")
send("e")
send("e")
send("e")
send("u")
send("n")
send("incorporate all")
send("la machine")
send("e")
send("s")
send("e")
