-- Custom grow function for the green pepper
local function customGreenPepperStart(self)
    Plant:cleanplot_amish()
    Plant:aerate( "Serinth air", 58)
    Plant:water( "Atlantis water", 29)
    Plant:spray( "Hunch pesticide", 70)
    Plant:aerate( "Detroit air", 5)
    Plant:spray( "Mount Perplexus pesticide", 104)
    Plant:fertilize( "Happy Ed's fertilizer", 11)
    Plant:water( "Wayhaven water", 21)
    Plant:spread( "Der'thalas neutralizer", 116)
    Plant:spread( "Garou neutralizer", 135)
    Plant:water( "Gulf of Mexico water", 31)
    Plant:fertilize( "Alphabet fertilizer", 105)
    Plant:spread( "Burns brand neutralizer", 123)
    Plant:spray( "Ant Cave pesticide", 21)
    Plant:aerate( "Genlab air", 38)
    Plant:water( "R'lyeh water", 33)
    Plant:fertilize( "Hippie fertilizer", 21)
    Plant:fertilize( "Smurfy fertilizer", 46)
    Plant:spread( "Cowville neutralizer", 44)
    Plant:aerate( "Ryogi-Pei air", 45)
    Plant:spray( "Murus Faralain pesticide", 45)
end

local function customGreenPepperGrow(self)
    Plant:cleanplot_amish()
    Plant:aerate( "Serinth air", 58)
    Plant:water( "Atlantis water", 29)
    Plant:spray( "Hunch pesticide", 70)
    Plant:aerate( "Detroit air", 5)
    Plant:spray( "Mount Perplexus pesticide", 104)
    Plant:fertilize( "Happy Ed's fertilizer", 11)
    Plant:water( "Wayhaven water", 21)
    Plant:spread( "Der'thalas neutralizer", 116)
    Plant:spread( "Garou neutralizer", 135)
    Plant:water( "Gulf of Mexico water", 31)
    Plant:fertilize( "Alphabet fertilizer", 105)
    Plant:spread( "Burns brand neutralizer", 123)
    Plant:spray( "Ant Cave pesticide", 21)
    Plant:aerate( "Genlab air", 38)
    Plant:water( "R'lyeh water", 33)
    Plant:fertilize( "Hippie fertilizer", 21)
    Plant:fertilize( "Smurfy fertilizer", 46)
    Plant:spread( "Cowville neutralizer", 44)
    Plant:aerate( "Ryogi-Pei air", 45)
    Plant:spray( "Murus Faralain pesticide", 45)
end

-- Add instances of Plant to the table
plants["green pepper"] = Plant:new("green pepper")
-- Assign the custom grow function to the "green pepper" instance
plants["green pepper"].start = customGreenPepperStart
plants["green pepper"].grow = customGreenPepperGrow