-- Custom grow function for the new potato
local function customNewPotatoStart(self)
    Plant:cleanplot_amish()
    Plant:spread( "Burns brand neutralizer", 127)
    Plant:spray( "Murus Faralain pesticide", 3)
    Plant:water( "Gulf of Mexico water", 60)
	Plant:spread( "Garou neutralizer", 133)
	Plant:spray( "Hunch pesticide", 40)
	Plant:fertilize( "Smurfy fertilizer", 31)
	Plant:water( "Atlantis water", 32)
	Plant:water( "Wayhaven water", 13)
	Plant:spread( "Cowville neutralizer", 103)
	Plant:aerate( "Serinth air", 22)
	Plant:fertilize( "Hippie fertilizer", 102)
	Plant:spread( "Der'thalas neutralizer", 105)
	Plant:spray( "Mount Perplexus pesticide", 2)
	Plant:water( "R'lyeh water", 25)
	Plant:fertilize( "Happy Ed's fertilizer", 78)
	Plant:aerate( "Genlab air", 35)
	Plant:aerate( "Ryogi-Pei air", 57)
	Plant:spray( "Ant Cave pesticide", 7)
	Plant:aerate( "Detroit air", 2)
	Plant:fertilize( "Alphabet fertilizer", 42)
end

local function customNewPotatoGrow(self)
    Plant:cleanplot_amish()
    Plant:spread( "Burns brand neutralizer", 127)
    Plant:spray( "Murus Faralain pesticide", 3)
    Plant:water( "Gulf of Mexico water", 60)
	Plant:spread( "Garou neutralizer", 133)
	Plant:spray( "Hunch pesticide", 40)
	Plant:fertilize( "Smurfy fertilizer", 31)
	Plant:water( "Atlantis water", 32)
	Plant:water( "Wayhaven water", 13)
	Plant:spread( "Cowville neutralizer", 103)
	Plant:aerate( "Serinth air", 22)
	Plant:fertilize( "Hippie fertilizer", 102)
	Plant:spread( "Der'thalas neutralizer", 105)
	Plant:spray( "Mount Perplexus pesticide", 2)
	Plant:water( "R'lyeh water", 25)
	Plant:fertilize( "Happy Ed's fertilizer", 78)
	Plant:aerate( "Genlab air", 35)
	Plant:aerate( "Ryogi-Pei air", 57)
	Plant:spray( "Ant Cave pesticide", 7)
	Plant:aerate( "Detroit air", 2)
	Plant:fertilize( "Alphabet fertilizer", 42)
end

-- Add instances of Plant to the table
plants["new potato"] = Plant:new("new potato")
-- Assign the custom grow function to the "new potato" instance
plants["new potato"].start = customNewPotatoStart
plants["new potato"].grow = customNewPotatoGrow