name: 3Klient Package Release Build

on:
  push:
    branches:
      - main
      - 'releases/**'
jobs:
  Build:
    runs-on: ubuntu-latest
    container:
      image: demonnic/muddler
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build mpackage
        run: |
          echo $PWD
          ls -l
          java -jar /app
          ls -l build

