name: 3Klient Package Release Build

on:
  push:
    branches:
      - main
      - 'releases/**'
jobs:
  Build:
    runs-on: ubuntu-latest
    container:
      image: demonnic/muddler
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build mpackage
        run: |
          echo $PWD
          ls -l
          java -jar /app
          ls -l build
      - name: Publish mpackage to Releases
        id: publish
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v0.0.1  # Specify your desired tag version
          release_name: Release v0.0.1  # Specify release name
          body: |
            Test Release of 3Klient mpackage release
          draft: false
          prerelease: true
          
      # Optionally, you can include steps to upload artifacts, such as your mpackage file, to the release.
      
      - name: Upload mpackage
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.publish.outputs.upload_url }}
          asset_path: build/3Klient.mpackage
          asset_name: 3Klient.mpackage
          asset_content_type: application/octet-stream
