name: 3Klient Package Release Build

on:
  push:
    branches:
      - main
      - 'releases/**'
jobs:
  Checkout:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout github-actions
        uses: actions/checkout@v3
  Build:
    needs: Checkout
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup Working Directory
        run: |
          echo $PWD
          docker run -T -u $(id -u):$(id -g) -v $PWD:/$PWD -w /$PWD demonnic/muddler
          ls -l build

